name: ✨ Feature Request
description: Suggest an idea
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Is your feature request related to a problem? If so, please provide a clear and concise description of the problem."
    validations:
      required: true
  - type: textarea
    id: desired-behavior
    attributes:
      label: Desired Behavior
      description: Provide a clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
