name: Something else
description: Support requests or general questions
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description your question or issue.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Provide any additional information or screenshots that may be relevant or helpful.
