module.exports = {
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier',
  ],
  parser: '@typescript-eslint/parser',
  plugins: [
    '@typescript-eslint/eslint-plugin',
    'import',
    'prettier',
  ],
  root: true,
  env: {
    node: true,
  },
  ignorePatterns: ['.eslintrc.js'],
  rules: {
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/explicit-module-boundary-types': 'off',
    '@typescript-eslint/interface-name-prefix': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
    'comma-dangle': [ 'error', {
      'arrays': 'always-multiline',
      'exports': 'always-multiline',
      'functions': 'always-multiline',
      'imports': 'always-multiline',
      'objects': 'always-multiline',
    } ],
    'import/newline-after-import': [ 'error', { 'count': 1 } ],
    'import/no-anonymous-default-export': 'off',
    'import/no-cycle': 1,
    'import/no-self-import': 1,
    'import/order': [ 'error', {
      'alphabetize': {
        'caseInsensitive': true,
        'order': 'asc',
      },
      'newlines-between': 'always',
      'groups': [
        'builtin',
        'external',
        'parent',
        'sibling',
        'index',
      ],
    },
    ],
    'no-unused-expressions': 2,
    'object-curly-spacing': [ 'error', 'always' ],
    'prettier/prettier': ['error'],
    'quotes': [ 'error', 'single', { 'allowTemplateLiterals': true } ],
    'semi': [ 'error', 'never' ],
  },
};
