name: 'Lint'

on:
  workflow_call:

permissions:
  checks: write
  contents: write

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        id: setup
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        id: dependencies
        run: npm ci

      - name: Prisma Generate
        id: db_generate
        run: npm run db:generate

      - name: Lint
        id: lint
        run: npm run lint
